<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChaletSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('chalets')->insert([
            [
                'name' => 'شاليه الشاطئ الذهبي',
                'code' => 'CH001',
                'pass_code' => '123456',
                'floor' => 'الأرضي',
                'building' => 'مبنى أ',
                'location' => 'شاطئ البحر الأحمر - الغردقة',
                'description' => 'شاليه فاخر بإطلالة مباشرة على البحر، يحتوي على غرفتي نوم، مطبخ مجهز، وتراس خاص',
                'status' => 'available',
                'type' => 'apartment',
                'is_cleaned' => true,
                'is_booked' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'فيلا النخيل',
                'code' => 'CH002',
                'pass_code' => '123456',
                'floor' => 'مستقل',
                'building' => 'فيلا منفصلة',
                'location' => 'عين السخنة - الساحل الشمالي',
                'description' => 'فيلا خاصة مع حديقة، مسبح خاص، 3 غرف نوم، ومطبخ خارجي',
                'status' => 'available',
                'type' => 'villa',
                'is_cleaned' => true,
                'is_booked' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'استوديو المرسى',
                'code' => 'CH003',
                'pass_code' => '123456',
                'floor' => 'الطابق الثالث',
                'building' => 'مبنى ب',
                'location' => 'المرسى - الإسكندرية',
                'description' => 'استوديو أنيق مع إطلالة على الميناء، غرفة نوم واحدة، ومطبخ مدمج',
                'status' => 'unavailable',
                'type' => 'studio',
                'is_cleaned' => false,
                'is_booked' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'شاليه المرجان',
                'code' => 'CH004',
                'pass_code' => '123456',
                'floor' => 'الطابق الثاني',
                'building' => 'مبنى ج',
                'location' => 'شرم الشيخ - جنوب سيناء',
                'description' => 'شاليه مع إطلالة على الشعاب المرجانية، غرفتي نوم، ومسبح مشترك',
                'status' => 'available',
                'type' => 'apartment',
                'is_cleaned' => true,
                'is_booked' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'فيلا الجبل الأخضر',
                'code' => 'CH005',
                'pass_code' => '123456',
                'floor' => 'مستقل',
                'building' => 'فيلا منفصلة',
                'location' => 'دهب - جنوب سيناء',
                'description' => 'فيلا جبلية مع إطلالة بانورامية، 4 غرف نوم، حديقة كبيرة، ومطبخ خارجي',
                'status' => 'available',
                'type' => 'villa',
                'is_cleaned' => true,
                'is_booked' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'استوديو الكورنيش',
                'code' => 'CH006',
                'pass_code' => '123456',
                'floor' => 'الطابق الأول',
                'building' => 'مبنى د',
                'location' => 'كورنيش الإسكندرية',
                'description' => 'استوديو حديث مع إطلالة على البحر المتوسط، غرفة نوم واحدة، ومطبخ مجهز',
                'status' => 'unavailable',
                'type' => 'studio',
                'is_cleaned' => false,
                'is_booked' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'شاليه الواحة',
                'code' => 'CH007',
                'pass_code' => '123456',
                'floor' => 'الأرضي',
                'building' => 'مبنى ه',
                'location' => 'سيوة - مطروح',
                'description' => 'شاليه في واحة سيوة، غرفتي نوم، حديقة خاصة، ومطبخ تقليدي',
                'status' => 'available',
                'type' => 'apartment',
                'is_cleaned' => true,
                'is_booked' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'فيلا الصحراء الذهبية',
                'code' => 'CH008',
                'pass_code' => '123456',
                'floor' => 'مستقل',
                'building' => 'فيلا منفصلة',
                'location' => 'البحر الأحمر - مرسى علم',
                'description' => 'فيلا صحراوية فاخرة، 5 غرف نوم، مسبح لا نهائي، ومطبخ خارجي كبير',
                'status' => 'available',
                'type' => 'villa',
                'is_cleaned' => true,
                'is_booked' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
